services:
  - type: web
    name: lung-disease-predection
    env: python
    buildCommand: "apt-get install -y libsndfile1 ffmpeg && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"